---
title: "Accommodation"
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: no
    self_contained: yes
    toc: no
    toc_depth: 2
    toc_float: yes
---

::: {#hello .greeting .message style="color: #DD0000; background-color: #FFEEEE; margin-top: 10px; padding-top: 10px; padding-left: 15px; padding-right: 15px; padding-bottom: 5px; margin-bottom: 10px; font-weight:bold;"}
WARNING: There are spam emails from "travellerpoint.org" targeting participants of CEN 2023. The emails ask to provide arrival and departure dates and credit card details. Do not reply to these scam emails and do not provide any personal information!
:::

Hotels can be booked through [Basel Tourism's website](https://basel.com/en/Basel/ukv/?doSearch=1&date_from=03.09.2023&date_to=07.09.2023&number_adult[]=1&doRadiusSearch=1&RadiusSearchLocationID=TDS00020011757239816&serviceProviderTypes[]=WBX00020010000100231&serviceProviderTypes[]=WBX00020010000100214&reset=1) for the conference. The BaselCard is offered as a free bonus with every booking at a Basel hotel, hostel, bed and breakfast or apartment. You will receive your personal guest card when you check in, and you can also load it to your smartphone as a web app. 
The BaselCard app works mostly offline and offers the same free services and discounts. In its electronic version, the guest card also features an interactive city map. For more information, see
[www.basel.com/en/baselcard](https://www.basel.com/en/baselcard).


In addition, the following hotels had conference contintents booked. Some are still open for bookings independent of the contingents from 3<sup>rd</sup> to 7<sup>th</sup> of September 2023 (4 nights):

### [Hotel Ibis Bahnhof Basel, 2*](https://all.accor.com/hotel/6510/index.en.shtml)
**Location:** Margarethenstrasse 35, 4053 Basel (3 minutes walk to Bahnhof SBB, ~25 minutes to venue by tram)  
<span style="color:lightgray">**Rate:** CHF 135.- (breakfast not included)</span>  Conference contingent expired.  
**Booking:** Write an e-mail to [H6510@accor.com](mailto:H6510@accor.com) oder call (+41 61 201 07 07) <span style="color:lightgray">with booking code "CEN2023 Conference"</span>  

### [Motel One, 3*](https://www.motel-one.com/en/hotels/basel/hotel-basel/)
**Location:** Barfüssergasse 16, 4051 Basel (~9 tram trip to Bahnhof SBB, ~15 minutes to venue by tram)  
<span style="color:lightgray">**Rate:** 03.-04.09.2023 - CHF 148.50, Rate: 04.-07.09.2023 - CHF 178.50 per night in THE ONE Queen (breakfast included)</span>   
Conference contingent expired.  
**Booking:** Write an e-mail to [res.basel@motel-one.com](mailto:res.basel@motel-one.com) <span style="color:lightgray">with keyword "CEN2023 Conference"</span>  

### [Hotel Odelya, 3*](https://www.odelya.ch)
**Location:** Missionsstrasse 21, 4055 Basel (9 min walk from venue)  
<span style="color:lightgray">**Rate:** CHF 160/200.- for single/double room (including breakfast)</span> Conference contingent SOLD OUT.  
**Booking:** Write an e-mail to [hotel@odelya.ch](mailto:hotel@odelya.ch) or call (+41 61 260 21 21) <span style="color:lightgray">with keyword "CEN2023 Conference"</span>  

### [Hotel D, 4*](https://www.hoteld-basel.ch/) 
**Location:** Blumenrain 19, 4051 Basel (11 min walk from venue)  
<span style="color:lightgray">**Rate:** CHF 157.- for single room (inclusive breakfast)</span> Conference contingent SOLD OUT.  
<span style="color:lightgray">**Booking:** You can book online with promo code CEN2023</span>  

### [Hotel Spalentor, 4*](https://www.hotelspalentor.ch)
**Location:** Schönbeinstrasse 1, 4056 Basel (8 min walk from venue)  
<span style="color:lightgray">**Rate:** Approx. CHF 170.- (including breakfast)</span> <span style="color:red">SOLD OUT</span>  
<span style="color:lightgray">**Booking:** Write an e-mail to [<span style="color:lightgray">info@hotelspalentor.ch</span>](mailto:info@hotelspalentor.ch) or call (+41 61 262 26 26) with keyword "CEN2023 Conference".</span>  
